= Miscellaneous Utils
This repo contains several utils, e. g. for Linux

== ZeroOneBooleanAdapter
When using cxf-wsdl2java, the *source* file `ZeroOneBooleanAdapter.java` might be missing in the classpath. The contained script provides a quick fix when using maven.
Just execute the attached script and add the following dependency to the cxf plugin in your pom.xml:
[source,xml]
----
<plugin>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-codegen-plugin</artifactId>
	...
	<executions>
	...
	</executions>
	<dependencies>
		<dependency>
			<groupId>de.sebastiankopp.helpers</groupId>
			<artifactId>zba-jaxb-res</artifactId>
			<version>1.0</version>
		</dependency>
	</dependencies>
</plugin>
----

== Installing Java from tgz archives (`install_java_from_tgz`)
Contains a short manual describing the required steps for installing java from a tgz archive as well as switching between already installed java runtimes (and JDKs).

== Watching and executing simple makefiles (`watch_and_execute`)
Simple tool for auto-executing makefiles after saving your workfile (it is intended to be used for rather small builds (especially LaTeX od AsciiDoc) than giant projects...)

Simple compile the java file using `javac`, then execute it!

NOTE: You have to use at least Java 9
